
[terminal.shell]
program = "/usr/bin/zsh"

[font]
size = 8.0
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }

[general]
import = [
    "~/.config/alacritty/themes/gruvbox_dark.toml"
]

[terminal]

